### ISSUE TITLE
Principle 8 - Ethics 

### ISSUE THREAD

**Issue by dlevineBC** [bcgov/digital-principles#1]
> Principle 8: Manage Risks Appropriately
> Respect security, privacy and **ethics**, balancing them with the imperative for swift action...

I would caution against lumping ethics in with security and privacy under risk management. These two areas have legislated and regulated requirements, but ethics is a different matter of concern. Ethics shouldn't be compromised for swift action

**Comment by rumoncarter** [comment]
I like this, by the by. Thank you.



Rumon Carter
Executive Director, Exchange Lab
Government of British Columbia
(250) 896-2329
@rumon



-------- Original message --------

**Comment by Bruce-N-Smith** [comment]
Good point Davis, I think it's reasonable to claim the impacts of poor ethics are larger and occur on a longer time scale than security and privacy. In addition, security and privacy are often easier to reduce to pragmatic binaries of private/not private or secure/not secure, for the sake of short term decisions.

It's very difficult to know if a group is/is not behaving ethically. It requires a lot of patient listening to many stakeholders across a shifting spectrum of "insiders/outsiders", who all have access to different privileges and powers. It also requires a lot of reflection and re-calibration in the face of many variables.

That being said, I like that the concept of ethics is included in these principles. I also understand it's good to keep a list of principles short (7-12 items), to help keep the cognitive load light for readers. So perhaps the next question becomes, 'where do we include ethics in these principles?'.

> 
> 
> > Principle 8: Manage Risks Appropriately
> > Respect security, privacy and **ethics**, balancing them with the imperative for swift action...
> 
> I would caution against lumping ethics in with security and privacy under risk management. These two areas have legislated and regulated requirements, but ethics is a different matter of concern. Ethics shouldn't be compromised for swift action

**Comment by dlevineBC** [comment]
Ethics is briefly mentioned in principle 3:

> 3. Embed inclusion
> Apply the highest standards of accessibility, inclusion and **ethics** at every stage of product and service design, development and delivery.

Similar to my first sentiment, I'm not sure if this the most appropriate fit either. 

I wonder what are we trying to say about ethics in these principles. And what existing core policies speak to questions of ethics? Ethics conversations I've heard in the BCPS has focused on ethics in how we work internally, with things like conflict of interest etc. 

I come from a perspective of how we conduct research with people and the ethical considerations of research. But I don't know if this was the original intent. Maybe rather than referring to ethics as a grand concept we can highlight what it means in the context of each principle? For example:

Principle 2: Design with People - what are the ethical implications of researching and designing with people?

Principle 10: What are the ethical standards when working with Indigenous communities and other equity seeking groups?

**Comment by Bruce-N-Smith** [comment]
Thanks and this is sounding good as a path forward: "rather than referring to ethics as a grand concept we can highlight what it means in the context of each principle"

**Comment by Kathleen-Assaf** [comment]
I really agree with Davis's comment - rather than reinforcing requirements set out in policy (e.g. CPPM, risk management) or aspirations expressed in strategy and values (e.g. Where ideas work, public service values), I would love to have principles 8, 9 and 10 be more specifically digital.

**Comment by sarabose** [comment]
Thank you to everyone who contributed to this fantastic discussion. I'm pleased to say that we've introduced a principle on ethics--Principle 3 in v. 0.2. We know that this principle may need to be refined, but we hope it's a good start and look forward to receiving feedback on it.
