### ISSUE TITLE
Principle 5 - Work in the open

### ISSUE THREAD

**Issue by AlexanderRitchie** [bcgov/digital-principles#10]
Really appreciate everything about this. There is some duplicity (though may have been intentional.
'Adopt open standards to facilitate interoperability and scalability' & 'default towards ... open and interoperable standards'.

Also mindful that the piece 'release open data and APIs' might presume that APIs are only for open data or that open is the only important form of data access beyond locked down.

Data access/sharing/exchange should be highlighted under the concept of interoperability in Principle 6.

AND, would comment that while API is an acronym that more people know, it certainly is tech centric language and is really a technology enabler to interoperability and access/sharing/exchange with any level of defined access control - might be more appropriate for the upcoming Technology Code of Practice than Digital Principles which are not tech audience specific.

**Comment by sarabose** [comment]
This is great feedback, and we've made some edits to principles 5 & 6 in v. 0.2 to reflect it and other feedback we received. Let us know if you don't think the changes quite hit the mark.

**Comment by AlexanderRitchie** [comment]
I like the new approach of the messages for both principles 5&6.

Thanks!
