### ISSUE TITLE
Principle 8 - Manage risks appropriately

### ISSUE THREAD

**Issue by AlexanderRitchie** [bcgov/digital-principles#11]
First half of the principle reads to me as if addressing security, privacy and ethics is in conflict with swift action as opposed to building those into the practice of delivering regularly (swift action) for comprehensive risk mitigation.

Second half of the principle reads to me as to need to manage risk of the iterative and agile delivery approach --> we have been learning through recent experience that taking an iterative and agile approach to delivery IS a risk mitigation strategy.

**Comment by sarabose** [comment]
Hi Alex, Principle 8 has been rephrased in v. 0.2. Have a look and let us know whether or not this addresses your comments satisfactorily.

**Comment by AlexanderRitchie** [comment]
Looks good to me. Thanks!
