### ISSUE TITLE
9. Commit to building internal capacity 

### ISSUE THREAD

**Issue by ksingbeil** [bcgov/digital-principles#3]
First off - so great to see these principles on Git. 

What about teams? I wonder if the principles could more clearly advocate for multi-disciplinary teams and the variety of perspectives, skill sets and approaches a diverse team can bring to a problem space. #9 is the only principle that mentions teams, but I don't think it goes far enough.

**Comment by boydjaimie** [comment]
Great note and yes, I agree it’s an omission in the current iteration. Please feel free to propose language... otherwise we’ll spin something up!

**Comment by ksingbeil** [comment]
Here's a go...

9. Build diverse teams and internal capacity
Empower all public servants to deliver excellent digital services; create and support teams with diverse skillsets, providing them with technology, tools and training; encourage innovation and controlled experimentation; build an organizational culture that supports constant learning

**Comment by Bruce-N-Smith** [comment]
This is sounding good! Some more ideas in this line of thinking:
~ "...providing them with quick and affordable access to technology, tools and training..."
~ create opportunities for public servants to share skills with the public at free not-for-profit events

> 
> 
> Here's a go...
> 
>     1. Build diverse teams and internal capacity
>        Empower all public servants to deliver excellent digital services; create and support teams with diverse skillsets, providing them with technology, tools and training; encourage innovation and controlled experimentation; build an organizational culture that supports constant learning

**Comment by Kathleen-Assaf** [comment]
I like the principle but it reiterates the corporate plan/HR strategy: https://www2.gov.bc.ca/assets/gov/careers/forms-tools/all-employees/corporate_plan_where_ideas_work.pdf   Should these principles be specifically digital and not overlap?

**Comment by sarabose** [comment]
We've made some significant changes to Principle 9 in v. 0.2. Please have a look and let us know if you think further edits are required.
