### ISSUE TITLE
Service consistency

### ISSUE THREAD

**Issue by jlabelle** [bcgov/digital-principles#4]
Another area I think could be emphasized more is consistency, to support enterprise solutions and universal service delivery. Suggest minor tweaks in **bold** to #1 and 6

1. Prioritize delivering impact for British Columbians
Government exists to improve peoples’ lives. Digital services should support this goal. Focus on citizens’ needs; build services for outcomes rather than outputs; deliver **consistent** and sustainable services through judicious use of public resources.
6. Take an ecosystem approach
Design and deliver solutions that are forward-thinking, adaptable and scalable; reuse before re-creating; support common components, interoperability and **enterprise approaches where appropriate**.

**Comment by glam-bert** [comment]
Agree with edits to Take an ecosystem approach.
