### ISSUE TITLE
Principle 1 - Are/should these principles be machine readable? (discussion)

### ISSUE THREAD

**Issue by Bruce-N-Smith** [bcgov/digital-principles#6]
In this age of automation, machine learning (ML) and artificial intelligence (AI) should we be attempting to write principles/policies so that machines can recognize, interpret and act with them?

If our adoption of GitHub represents a step towards [government policy-as-code](http://www.slaw.ca/2019/06/14/the-fight-over-rules-as-code/), should a machine be able to: 
- take a principle (a chunk of text suggesting rules); 
- use it to test other chunks of text (laws, policies, procedures, code, data, communications, reports, etc.); and 
- identify potential issues?

Having done that perhaps an automated agent could summarize how compliant (H/M/L) it thinks a chunk of text is with the principles?

Expecting a robot to do complex analysis like this today may be unrealistic, but as our set of policy grows having it written in a way that encourages future automation could be a big help. There are already examples of natural language processing (NLP) and sentiment analysis being used to sort chunks of text into different sets for human experts to analyze further. Perhaps we should have some coders and data scientists evaluate these principles from that perspective?

One tiny example of this could be the following line from Principle 1, "Government exists to improve peoples’ lives. Digital services should support this goal." The rest of the principles are written as more direct commands, which makes this statement stand out as slightly different.

**Comment by sarabose** [comment]
Hi Bruce, it would be interesting to have a larger discussion on this issue. In the meantime, I believe the edits we've made to Principle 1 in v. 0.2 address the example you flagged.

**Comment by Bruce-N-Smith** [comment]
Thanks Sara! I didn't see an automated notification of your response 17 days ago, but thanks for the reply, I appreciate it.
