### ISSUE TITLE
Principle 6 - ecosystem - contributing 

### ISSUE THREAD

**Issue by watkinspd** [bcgov/digital-principles#7]
Suggestion: Principle 6 - Ecosystem, should include the idea of publishing work with the aim of contributing it to the community. Which means it has the attributes, features, information... that community would need in order to make use of it.

**Comment by sarabose** [comment]
Thanks for the suggestion, Peter. We've revised Principle 6 in v. 0.2 to reflect feedback from you and others. Happy to iterate on it further as needed!
