### ISSUE TITLE
7. Act as trusted information stewards

### ISSUE THREAD

**Issue by glam-bert** [bcgov/digital-principles#9]
The title implies that the content would include proportionate protection of data and information, as well as use. That seems to be covered more in principle 8; perhaps the two could be merged or the title of this once could be updated to focus on deriving value from information including data.

**Comment by jpfournier** [comment]
Agreed. Much of the conversation about data focuses on risks, but there would be value in a principle that sets the expectation for data use and re-use.

**Comment by HeatherRemacle** [comment]
Agreed as well. Listening to Tim O'Reilly discuss data, government, and trust, I like the focus on **outcomes** for the use of data. (https://www.oreilly.com/tim/wtf-book.html)

For example, people are okay with Google using location data in a way that delivers better service. They are not okay with data being used to spam them. 

Other reflections: 

How can we be transparent about the use of data, and ensure that the use reflects the users's needs and interests? It is also important to give the user the ability to direct the use of their data, as we cannot always know what is in their interest.

**Comment by sarabose** [comment]
Principle 7 has been updated in v. 0.2--let us know if you think further refinements are needed
